### ISSUE TITLE
最新flutter无法使用

### ISSUE THREAD

**Issue by orchie** [OpenFlutter/flutter_oktoast#31]
## 环境
win10 64,
Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (11 days ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0
## 代码
showToast("content");
## 报错
```
E/flutter (14566): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Bad state: No element
E/flutter (14566): #0      Iterable.first (dart:core/iterable.dart:518:7)
E/flutter (14566): #1      showToast (package:oktoast/src/core/toast.dart:39:34)
E/flutter (14566): #2      _LoginState.build.<anonymous closure> (package:myapp/page/login.dart:184:27)
E/flutter (14566): <asynchronous suspension>
E/flutter (14566): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
E/flutter (14566): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
E/flutter (14566): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (14566): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (14566): #7      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
E/flutter (14566): #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (14566): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (14566): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (14566): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (14566): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (14566): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (14566): #14     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (14566): #15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (14566): #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (14566): #17     _invoke1 (dart:ui/hooks.dart:250:10)
E/flutter (14566): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
E/flutter (14566):
```
大佬help一下 ~~

**Comment by CaiJingLong** [comment]
https://github.com/OpenFlutter/flutter_oktoast/blob/master/README.md#3-wrap-your-app-widget

**Comment by orchie** [comment]
thanks...我瞎了...
